---
- name: Recopilar informacion detallada del servidor y version de Python
  hosts: all
  become: no
  gather_facts: true

  tasks:
    # Tarea 1: Mostrar informacion basica del sistema
    - name: Mostrar hechos del sistema operativo
      ansible.builtin.debug:
        msg: |
          Nombre del OS: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}
          Kernel: {{ ansible_facts['kernel'] }}
          Familia del OS: {{ ansible_facts['os_family'] }}
      tags:
        - info
    
    # Tarea 2: Obtener la version de Python del sistema
    - name: Obtener la version de Python
      ansible.builtin.command: python3 --version
      register: python_version
      changed_when: false
      ignore_errors: true
      tags:
        - python
        - info
    
    # Tarea 3: Mostrar la version de Python si se encontro
    - name: Mostrar version de Python si esta instalada
      ansible.builtin.debug:
        msg: "Version de Python: {{ python_version.stdout }}"
      when: python_version.rc == 0
      tags:
        - python
        - info
        
    # Tarea 4: Obtener la informacion de los discos con el comando lsblk
    - name: Obtener informacion de los discos con lsblk
      ansible.builtin.shell: lsblk -J
      register: disk_info_shell
      changed_when: false
      tags:
        - disk
        - info

    # Tarea 5: Mostrar la informacion de los discos
    - name: Mostrar informacion de los discos
      ansible.builtin.debug:
        msg: "{{ disk_info_shell.stdout | from_json }}"
      tags:
        - disk
        - info
